// Generated by scripts/generate-atlas-map.mjs with landPath.ts. Do not edit by hand.
// Kept apart from the coastlines so pages can place things on the map without loading them.

/** The part of the world the map draws, in degrees. */
export const BOUNDS = {"west":60,"east":175,"south":-12,"north":55} as const

/** The map's coordinate space (SVG viewBox), in map units. */
export const MAP_WIDTH = 872
export const MAP_HEIGHT = 593
